package ebay.api.paypalapi;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-05-22T17:22:02.108+02:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "PayPalAPIInterfaceService", 
                  wsdlLocation = "http://www.paypalobjects.com/wsdl/PayPalSvc.wsdl",
                  targetNamespace = "urn:ebay:api:PayPalAPI") 
public class PayPalAPIInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:ebay:api:PayPalAPI", "PayPalAPIInterfaceService");
    public final static QName PayPalAPI = new QName("urn:ebay:api:PayPalAPI", "PayPalAPI");
    public final static QName PayPalAPIAA = new QName("urn:ebay:api:PayPalAPI", "PayPalAPIAA");
    static {
        URL url = null;
        try {
            url = new URL("http://www.paypalobjects.com/wsdl/PayPalSvc.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PayPalAPIInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.paypalobjects.com/wsdl/PayPalSvc.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PayPalAPIInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PayPalAPIInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PayPalAPIInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PayPalAPIInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PayPalAPIInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PayPalAPIInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PayPalAPIInterface
     */
    @WebEndpoint(name = "PayPalAPI")
    public PayPalAPIInterface getPayPalAPI() {
        return super.getPort(PayPalAPI, PayPalAPIInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PayPalAPIInterface
     */
    @WebEndpoint(name = "PayPalAPI")
    public PayPalAPIInterface getPayPalAPI(WebServiceFeature... features) {
        return super.getPort(PayPalAPI, PayPalAPIInterface.class, features);
    }
    /**
     *
     * @return
     *     returns PayPalAPIAAInterface
     */
    @WebEndpoint(name = "PayPalAPIAA")
    public PayPalAPIAAInterface getPayPalAPIAA() {
        return super.getPort(PayPalAPIAA, PayPalAPIAAInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PayPalAPIAAInterface
     */
    @WebEndpoint(name = "PayPalAPIAA")
    public PayPalAPIAAInterface getPayPalAPIAA(WebServiceFeature... features) {
        return super.getPort(PayPalAPIAA, PayPalAPIAAInterface.class, features);
    }

}
